/**
 * Templates pre-armados para portadas de sección. El dueño elige uno
 * en un click y queda con un look profesional sin tocar 20 controles.
 * Después puede ajustar individualmente (color, fuente, alineación,
 * overlay).
 *
 * Las imágenes de muestra son URLs externas (Unsplash) — el dueño
 * normalmente sube la suya. Si no sube, el template viene con un
 * placeholder visual.
 */

import type { SectionCoverConfig } from './section-cover-config';

export type SectionCoverTemplate = {
  id: string;
  name: string;
  /** Categoría visual sugerida (para agrupar en el picker). */
  category: 'dark' | 'vibrant' | 'minimal' | 'premium' | 'vintage' | 'fresh';
  /** Sample swatch para el thumbnail del picker. */
  swatch: { from: string; to: string };
  /** Config completa lista para aplicar. */
  config: Omit<SectionCoverConfig, 'bgImageUrl'> & {
    /** El template no fuerza una imagen — el dueño sube la suya.
     *  Si quiere usar el placeholder/demo, el editor maneja eso. */
    bgImageUrl: string | null;
  };
};

export const SECTION_COVER_TEMPLATES: SectionCoverTemplate[] = [
  {
    id: 'gourmet-dark',
    name: 'Gourmet Oscuro',
    category: 'dark',
    swatch: { from: '#0a0a0a', to: '#3a2818' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#0a0a0a',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(180deg, rgba(10,10,10,0.15) 0%, rgba(10,10,10,0.85) 100%)',
        opacity: 1,
      },
      height: 240,
      borderRadius: 16,
      align: 'left',
      verticalAlign: 'bottom',
      paddingX: 24,
      paddingY: 28,
      title: {
        color: '#FFFFFF',
        fontFamily: '"Playfair Display", Georgia, serif',
        fontWeight: 700,
        fontSize: 36,
        letterSpacing: -0.02,
        lineHeight: 1.05,
        shadow: { color: 'rgba(0,0,0,0.5)', blur: 10, offsetY: 2 },
        transform: 'none',
      },
      tagline: {
        color: 'rgba(255,255,255,0.85)',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1.4,
        shadow: null,
        transform: 'none',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'premium-gold',
    name: 'Premium Gold',
    category: 'premium',
    swatch: { from: '#000000', to: '#D4AF37' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#0d0d0d',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(180deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.7) 100%)',
        opacity: 1,
      },
      height: 220,
      borderRadius: 12,
      align: 'center',
      verticalAlign: 'middle',
      paddingX: 24,
      paddingY: 24,
      title: {
        color: '#D4AF37',
        fontFamily: '"Cormorant Garamond", serif',
        fontWeight: 700,
        fontSize: 38,
        letterSpacing: 0.08,
        lineHeight: 1.0,
        shadow: { color: 'rgba(0,0,0,0.6)', blur: 12, offsetY: 2 },
        transform: 'uppercase',
      },
      tagline: {
        color: 'rgba(212,175,55,0.85)',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: 12,
        letterSpacing: 0.2,
        lineHeight: 1.4,
        shadow: null,
        transform: 'uppercase',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'vibrante',
    name: 'Vibrante',
    category: 'vibrant',
    swatch: { from: '#F97316', to: '#EAB308' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#F97316',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(135deg, rgba(249,115,22,0.6) 0%, rgba(234,179,8,0.4) 100%)',
        opacity: 1,
      },
      height: 200,
      borderRadius: 20,
      align: 'left',
      verticalAlign: 'middle',
      paddingX: 24,
      paddingY: 20,
      title: {
        color: '#FFFFFF',
        fontFamily: '"Archivo Black", sans-serif',
        fontWeight: 400,
        fontSize: 36,
        letterSpacing: -0.01,
        lineHeight: 0.95,
        shadow: { color: 'rgba(0,0,0,0.3)', blur: 6, offsetY: 2 },
        transform: 'none',
      },
      tagline: {
        color: '#FFFFFF',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1.3,
        shadow: null,
        transform: 'none',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'minimal-claro',
    name: 'Minimal Claro',
    category: 'minimal',
    swatch: { from: '#FAFAF9', to: '#E7E5E4' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#FAFAF9',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: null,
      height: 180,
      borderRadius: 12,
      align: 'left',
      verticalAlign: 'middle',
      paddingX: 28,
      paddingY: 20,
      title: {
        color: '#111111',
        fontFamily: '"DM Serif Display", serif',
        fontWeight: 400,
        fontSize: 32,
        letterSpacing: -0.01,
        lineHeight: 1.05,
        shadow: null,
        transform: 'none',
      },
      tagline: {
        color: '#666666',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: 13,
        letterSpacing: 0,
        lineHeight: 1.4,
        shadow: null,
        transform: 'none',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'vintage-cafe',
    name: 'Vintage Café',
    category: 'vintage',
    swatch: { from: '#4A2C20', to: '#D4B896' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#4A2C20',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(180deg, rgba(74,44,32,0.3) 0%, rgba(74,44,32,0.8) 100%)',
        opacity: 1,
      },
      height: 220,
      borderRadius: 8,
      align: 'center',
      verticalAlign: 'middle',
      paddingX: 24,
      paddingY: 24,
      title: {
        color: '#F5EBDC',
        fontFamily: 'Lobster, cursive',
        fontWeight: 400,
        fontSize: 38,
        letterSpacing: 0,
        lineHeight: 1.0,
        shadow: { color: 'rgba(0,0,0,0.4)', blur: 6, offsetY: 2 },
        transform: 'none',
      },
      tagline: {
        color: '#D4B896',
        fontFamily: '"Cormorant Garamond", serif',
        fontWeight: 400,
        fontSize: 14,
        letterSpacing: 0.05,
        lineHeight: 1.4,
        shadow: null,
        transform: 'uppercase',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'fresh-fitness',
    name: 'Fresh Fitness',
    category: 'fresh',
    swatch: { from: '#06B6D4', to: '#A3E635' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#06B6D4',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(135deg, rgba(6,182,212,0.7) 0%, rgba(163,230,53,0.3) 100%)',
        opacity: 1,
      },
      height: 200,
      borderRadius: 20,
      align: 'left',
      verticalAlign: 'bottom',
      paddingX: 24,
      paddingY: 20,
      title: {
        color: '#FFFFFF',
        fontFamily: 'Montserrat, sans-serif',
        fontWeight: 900,
        fontSize: 34,
        letterSpacing: -0.02,
        lineHeight: 1.0,
        shadow: { color: 'rgba(0,0,0,0.25)', blur: 4, offsetY: 1 },
        transform: 'uppercase',
      },
      tagline: {
        color: '#FFFFFF',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 500,
        fontSize: 13,
        letterSpacing: 0.05,
        lineHeight: 1.3,
        shadow: null,
        transform: 'none',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'pasteleria-rosa',
    name: 'Pastelería Rosa',
    category: 'vibrant',
    swatch: { from: '#FCE7F3', to: '#EC4899' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#FCE7F3',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(180deg, rgba(252,231,243,0.1) 0%, rgba(236,72,153,0.5) 100%)',
        opacity: 1,
      },
      height: 210,
      borderRadius: 24,
      align: 'center',
      verticalAlign: 'middle',
      paddingX: 24,
      paddingY: 24,
      title: {
        color: '#FFFFFF',
        fontFamily: '"Great Vibes", cursive',
        fontWeight: 400,
        fontSize: 44,
        letterSpacing: 0,
        lineHeight: 1.0,
        shadow: { color: 'rgba(190,24,93,0.4)', blur: 8, offsetY: 2 },
        transform: 'none',
      },
      tagline: {
        color: 'rgba(255,255,255,0.95)',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 500,
        fontSize: 13,
        letterSpacing: 0.05,
        lineHeight: 1.4,
        shadow: null,
        transform: 'uppercase',
      },
      badge: null,
      badgeText: null,
    },
  },
  {
    id: 'nightclub',
    name: 'Nightclub',
    category: 'dark',
    swatch: { from: '#1E1B4B', to: '#EC4899' },
    config: {
      version: 1,
      bgImageUrl: null,
      bgColor: '#1E1B4B',
      bgFit: 'cover',
      bgPosition: 'center',
      overlay: {
        color: 'linear-gradient(135deg, rgba(30,27,75,0.7) 0%, rgba(236,72,153,0.4) 100%)',
        opacity: 1,
      },
      height: 240,
      borderRadius: 16,
      align: 'left',
      verticalAlign: 'bottom',
      paddingX: 24,
      paddingY: 28,
      title: {
        color: '#FFFFFF',
        fontFamily: '"Bebas Neue", Impact, sans-serif',
        fontWeight: 400,
        fontSize: 48,
        letterSpacing: 0.02,
        lineHeight: 0.9,
        shadow: { color: 'rgba(236,72,153,0.5)', blur: 12, offsetY: 0 },
        transform: 'uppercase',
      },
      tagline: {
        color: 'rgba(240,171,252,0.95)',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 500,
        fontSize: 13,
        letterSpacing: 0.15,
        lineHeight: 1.3,
        shadow: null,
        transform: 'uppercase',
      },
      badge: null,
      badgeText: null,
    },
  },
];

export const SECTION_COVER_CATEGORY_LABELS: Record<
  SectionCoverTemplate['category'],
  string
> = {
  dark: 'Oscuro',
  vibrant: 'Vibrante',
  minimal: 'Minimalista',
  premium: 'Premium',
  vintage: 'Vintage',
  fresh: 'Fresco',
};
